export const SHOE_LIST_REQUEST = 'SHOE_LIST_REQUEST';
export const SHOE_LIST_SUCCESS = 'SHOE_LIST_SUCCESS';
export const SHOE_LIST_FAIL = 'SHOE_LIST_FAIL';

export const SHOE_DETAILS_REQUEST = 'SHOE_DETAILS_REQUEST';
export const SHOE_DETAILS_SUCCESS = 'SHOE_DETAILS_SUCCESS';
export const SHOE_DETAILS_FAIL = 'SHOE_DETAILS_FAIL';

export const SHOE_SAVE_REQUEST = 'SHOE_SAVE_REQUEST';
export const SHOE_SAVE_SUCCESS = 'SHOE_SAVE_SUCCESS';
export const SHOE_SAVE_FAIL = 'SHOE_SAVE_FAIL';